#!/bin/bash -e

infiles=(
TTJets_nTuple.root
GJets_HT-200To400_nTuple.root
GJets_HT-400To600_nTuple.root
SinglePhoton_Run2015D-PromptReco-v4_nTuple.root
TTGJets_nTuple.root
GJets_HT-40To100_nTuple.root
GJets_HT-100To200_nTuple.root
ZGTo2LG_nTuple.root
WJetsToLNu_HT-100To200_nTuple.root
SinglePhoton_Run2015D-05Oct2015-v1_nTuple.root
WGToLNuG-madgraphMLM_nTuple.root
WGToLNuG_PtG-500_nTuple.root
GJets_HT-600ToInf_nTuple.root
WJetsToLNu_HT-200To400_nTuple.root
WGToLNuG-amcatnloFXFX_nTuple.root
WJetsToLNu_HT-600To800_nTuple.root
WJetsToLNu_HT-800To1200_nTuple.root
WJetsToLNu_HT-400To600_nTuple.root
ZNuNuGJets_MonoPhoton_PtG-130_nTuple.root
WJetsToLNu_HT-600ToInf_nTuple.root
GJet_Pt-15ToInf_nTuple.root
QCD_Pt-20to30_EMEnriched_nTuple.root
QCD_Pt-300toInf_EMEnriched_nTuple.root
JetHT_Run2015D-PromptReco-v4_nTuple.root
QCD_Pt-120to170_EMEnriched_nTuple.root
QCD_Pt-170to300_EMEnriched_nTuple.root
QCD_HT100to200_nTuple.root
QCD_Pt-80to120_EMEnriched_nTuple.root
SinglePhoton_Run2015C_25ns-05Oct2015-v1_nTuple.root
QCD_HT700to1000_nTuple.root
QCD_HT500to700_nTuple.root
WJetsToLNu_HT-2500ToInf_nTuple.root
QCD_Pt-30to50_EMEnriched_nTuple.root
WJetsToLNu_HT-1200To2500_nTuple.root
QCD_HT300to500_nTuple.root
JetHT_Run2015D-05Oct2015-v1_nTuple.root
QCD_Pt-50to80_EMEnriched_nTuple.root
QCD_HT200to300_nTuple.root
QCD_Pt-15to20_EMEnriched_nTuple.root
QCD_HT1500to2000_nTuple.root
QCD_HT1000to1500_nTuple.root
QCD_HT2000toInf_nTuple.root
ZJetsToNuNu_HT-200To400_nTuple.root
SMS-T5gg_mGluino-1400_mNeutralino-200_nTuple.root
SMS-T5gg_mGluino-1400_mNeutralino-1200_nTuple.root
ZJetsToNuNu_HT-100To200_nTuple.root
ZJetsToNuNu_HT-600ToInf_nTuple.root
ZJetsToNuNu_HT-400To600_nTuple.root
JetHT_Run2015C_25ns-05Oct2015-v1_nTuple.root
DYJetsToLL_M-50_nTuple.root
)

infiles=(
QCD_HT700to1000_nTuple.root
QCD_HT500to700_nTuple.root
QCD_HT1000to1500_nTuple.root
QCD_HT1500to2000_nTuple.root
GJets_HT-600ToInf_nTuple.root
QCD_HT2000toInf_nTuple.root
GJets_HT-400To600_nTuple.root
GJets_HT-200To400_nTuple.root
QCD_HT300to500_nTuple.root
QCD_HT100to200_nTuple.root
QCD_HT200to300_nTuple.root
GJets_HT-100To200_nTuple.root
GJets_HT-40To100_nTuple.root
)
# run with no input file first, to compile all versions
root -b -l -q run.C\(\"0\"\)
if [ $? -ne 0 ]; then
  exit
fi

# determine the number of cores(processes) which will be used
nCores=$(expr `nproc` - 1)

# start the submittion, and end if all jobs are submitted
while [ ${#infiles[@]} -ne 0 ]; do
  sleep 1

  # find out how many root processer are running
  nProcRunning=$(ps hu -C "root -b -l -q run.C"|wc -l)
  if [ "$nProcRunning" -lt "$nCores" ]; then
    root -b -l -q run.C\(\"/user/kiesel/nTuples/V07/${infiles[0]}\"\) &
    infiles=( ${infiles[@]:1:99} )
  fi

done

# after all jobs are sumbitted, monitor the jobs still running
while [[ $(ps hu -C "root -b -l -q run.C") ]]; do
  sleep 1
done

echo "DONE"
